version: '3'

services:
  app_db:
    image: 'mysql:8.0'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/entrypoint:/docker-entrypoint-initdb.d
