CREATE TABLE IF NOT EXISTS dbm_control (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    file VARCHAR(255) UNIQUE NOT NULL,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_id PRIMARY KEY(id)
)